spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update    # 최초 실행 후 validate 로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:local-dev-please-change-THIS-IS-NOT-PROD-SECRET-1234567890}
    access-token-validity: 1800000
    refresh-token-validity: 5184000000

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    userinfo-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8081/auth/callback/kakao
    #추후 구글, APPLE 로그인 추가 예정

  redirect:
    kakao:  http://localhost:8081/auth/callback/kakao
    google: ${GOOGLE_REDIRECT_URI:http://localhost:8081/auth/login/google/callback}
    apple:  ${APPLE_REDIRECT_URI:http://localhost:8081/auth/login/apple/callback}

server:
  port: 8081
  address: 0.0.0.0