name: Probe SSH
on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key via agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}  # 멀티라인 비밀키 원문

      - name: Add known_hosts (host key pinning)
        run: |
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            ssh-keyscan -p ${SSH_PORT:-22} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=yes ${USER}@${HOST} "echo ✅ Connected to $(hostname) as $(whoami)"
