name: Test SSH Connection

on:
  workflow_dispatch:   # 수동 실행 버튼 활성화

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and run uname
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ 서버 연결 성공"
            uname -a
