name: Test SSH Connection

on:
  workflow_dispatch:  # 수동 실행 버튼 활성화

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Try SSH to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            echo "✅ Connected to $(hostname) as $(whoami)"
            uname -a
            date
